# Generated by Django 4.1.5 on 2024-10-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('original_language_code', models.CharField(max_length=5)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('revenue', models.FloatField(default=0)),
                ('runtime', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Planned', 'Planned'), ('In Production', 'In Production'), ('Post Production', 'Post Production'), ('Released', 'Released'), ('Rumored', 'Rumored'), ('', '')], default='', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('languages', models.TextField()),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
                ('production_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.productioncompany')),
            ],
        ),
    ]
