# Generated by Django 4.1.5 on 2024-10-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_data',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie_data',
            old_name='production_company_id',
            new_name='production_company',
        ),
    ]
