# Generated by Django 4.1.5 on 2024-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_genre_id_movie_data_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_data',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie_data',
            name='production_company',
        ),
        migrations.AddField(
            model_name='movie_data',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie_data',
            name='production_company_id',
            field=models.IntegerField(default=0),
        ),
    ]
