# Generated by Django 4.1.5 on 2024-10-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_data_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
