# Generated by Django 4.1.5 on 2024-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_data_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
